//---------------------------------------------------------------------------

#ifndef Unit2H
#define Unit2H
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include "structures.h"
#include "split.h"
#include <math.h>
#include <Chart.hpp>
#include <ExtCtrls.hpp>
#include <Series.hpp>
#include <TeEngine.hpp>
#include <TeeProcs.hpp>
//---------------------------------------------------------------------------
class TForm2 : public TForm
{
__published:	// IDE-managed Components
        TPageControl *PageControl1;
        TTabSheet *TabUFS;
        TScrollBox *ScrollBox1;
        TChart *Chart1;
        TLineSeries *Series1;
        TChart *Chart2;
        TLineSeries *LineSeries1;
        TChart *Chart3;
        TLineSeries *LineSeries2;
        TChart *Chart4;
        TLineSeries *LineSeries3;
        TChart *Chart5;
        TLineSeries *LineSeries4;
        TTabSheet *TabFS;
        TScrollBox *ScrollBox2;
        TChart *Chart6;
        TLineSeries *LineSeries5;
        TChart *Chart7;
        TLineSeries *LineSeries6;
        TChart *Chart8;
        TLineSeries *LineSeries7;
        TTabSheet *TabSS;
        TScrollBox *ScrollBox3;
        TChart *Chart9;
        TLineSeries *LineSeries8;
        TChart *Chart10;
        TLineSeries *LineSeries9;
        TChart *Chart11;
        TLineSeries *LineSeries10;
        TChart *Chart12;
        TLineSeries *LineSeries11;
        TChart *Chart13;
        TLineSeries *LineSeries12;
        TChart *Chart14;
        TLineSeries *LineSeries13;
        TChart *Chart15;
        TLineSeries *LineSeries14;
        TChart *Chart16;
        TLineSeries *LineSeries15;
        TChart *Chart17;
        TLineSeries *LineSeries16;
        TChart *Chart18;
        TLineSeries *LineSeries17;
        TChart *Chart19;
        TLineSeries *LineSeries18;
        TTabSheet *TabSZS;
        TScrollBox *ScrollBox4;
        TChart *Chart20;
        TLineSeries *LineSeries19;
        TChart *Chart21;
        TLineSeries *LineSeries20;
        TChart *Chart22;
        TLineSeries *LineSeries21;
        TChart *Chart23;
        TLineSeries *LineSeries22;
        TChart *Chart24;
        TLineSeries *LineSeries23;
        TChart *Chart25;
        TLineSeries *LineSeries24;
        TChart *Chart26;
        TLineSeries *LineSeries25;
        TChart *Chart27;
        TLineSeries *LineSeries26;
        TChart *Chart28;
        TLineSeries *LineSeries27;
        TChart *Chart29;
        TLineSeries *LineSeries28;
        TChart *Chart30;
        TLineSeries *LineSeries29;
        TChart *Chart31;
        TLineSeries *LineSeries30;
        TChart *Chart32;
        TLineSeries *LineSeries31;
        TChart *Chart34;
        TLineSeries *LineSeries33;
        TChart *Chart33;
        TLineSeries *LineSeries32;
        TTabSheet *TabZS;
        TScrollBox *ScrollBox5;
        TChart *Chart35;
        TLineSeries *LineSeries34;
        TChart *Chart36;
        TLineSeries *LineSeries35;
        TChart *Chart37;
        TLineSeries *LineSeries36;
        TChart *Chart38;
        TLineSeries *LineSeries37;
        TChart *Chart39;
        TLineSeries *LineSeries38;
        TChart *Chart40;
        TLineSeries *LineSeries39;
        TChart *Chart41;
        TLineSeries *LineSeries40;
        TChart *Chart42;
        TLineSeries *LineSeries41;
        TTabSheet *TabZHZS;
        TScrollBox *ScrollBox6;
        TChart *Chart43;
        TLineSeries *LineSeries42;
        TChart *Chart44;
        TLineSeries *LineSeries43;
        TChart *Chart45;
        TLineSeries *LineSeries44;
        TChart *Chart46;
        TLineSeries *LineSeries45;
        TChart *Chart47;
        TLineSeries *LineSeries46;
        TChart *Chart48;
        TLineSeries *LineSeries47;
        TChart *Chart49;
        TLineSeries *LineSeries48;
        TChart *Chart50;
        TLineSeries *LineSeries49;
        TChart *Chart51;
        TLineSeries *LineSeries50;
        TChart *Chart52;
        TLineSeries *LineSeries51;
        TTabSheet *TabZHS;
        TScrollBox *ScrollBox7;
        TChart *Chart53;
        TLineSeries *LineSeries52;
        TChart *Chart54;
        TLineSeries *LineSeries53;
        TChart *Chart55;
        TLineSeries *LineSeries54;
        TChart *Chart56;
        TLineSeries *LineSeries55;
        TChart *Chart57;
        TLineSeries *LineSeries56;
        TChart *Chart58;
        TLineSeries *LineSeries57;
        TChart *Chart59;
        TLineSeries *LineSeries58;
        TChart *Chart60;
        TLineSeries *LineSeries59;
        TChart *Chart61;
        TLineSeries *LineSeries60;
        TChart *Chart62;
        TLineSeries *LineSeries61;
        TTabSheet *TabOS;
        TScrollBox *ScrollBox8;
        TChart *Chart63;
        TLineSeries *LineSeries62;
        TChart *Chart64;
        TLineSeries *LineSeries63;
        TChart *Chart65;
        TLineSeries *LineSeries64;
        TChart *Chart66;
        TLineSeries *LineSeries65;
        TChart *Chart67;
        TLineSeries *LineSeries66;
        TChart *Chart68;
        TLineSeries *LineSeries67;
        TChart *Chart69;
        TLineSeries *LineSeries68;
        TTabSheet *TabKS;
        TScrollBox *ScrollBox9;
        TChart *Chart70;
        TLineSeries *LineSeries69;
        TChart *Chart71;
        TLineSeries *LineSeries70;
        TChart *Chart72;
        TLineSeries *LineSeries71;
        TChart *Chart73;
        TLineSeries *LineSeries72;
        TChart *Chart74;
        TLineSeries *LineSeries73;
        TChart *Chart75;
        TLineSeries *LineSeries74;
        TChart *Chart76;
        TLineSeries *LineSeries75;
        TChart *Chart77;
        TLineSeries *LineSeries76;
        TTabSheet *TabIKS;
        TScrollBox *ScrollBox10;
        TChart *Chart78;
        TLineSeries *LineSeries77;
        TChart *Chart79;
        TLineSeries *LineSeries78;
        TChart *Chart80;
        TLineSeries *LineSeries79;
        TChart *Chart81;
        TLineSeries *LineSeries80;
        TChart *Chart82;
        TLineSeries *LineSeries81;
        TTabSheet *TabPS;
        TScrollBox *ScrollBox11;
        TChart *Chart83;
        TLineSeries *LineSeries82;
        TChart *Chart84;
        TLineSeries *LineSeries83;
        TChart *Chart85;
        TLineSeries *LineSeries84;
        TChart *Chart86;
        TLineSeries *LineSeries85;
        TChart *Chart87;
        TLineSeries *LineSeries86;
        TChart *Chart88;
        TLineSeries *LineSeries87;
        TChart *Chart89;
        TLineSeries *LineSeries88;
        TTabSheet *TabNS;
        TScrollBox *ScrollBox12;
        TChart *Chart90;
        TLineSeries *LineSeries89;
        TChart *Chart91;
        TLineSeries *LineSeries90;
        TChart *Chart92;
        TLineSeries *LineSeries91;
        TChart *Chart93;
        TLineSeries *LineSeries92;
        TChart *Chart94;
        TLineSeries *LineSeries93;
        TChart *Chart95;
        TLineSeries *LineSeries94;
        TChart *Chart96;
        TLineSeries *LineSeries95;
        TChart *Chart97;
        TLineSeries *LineSeries96;
        TChart *Chart98;
        TLineSeries *LineSeries97;
        TChart *Chart99;
        TLineSeries *LineSeries98;
        TChart *Chart100;
        TLineSeries *LineSeries99;
        TTabSheet *TabTS;
        TScrollBox *ScrollBox13;
        TChart *Chart101;
        TLineSeries *LineSeries100;
        TChart *Chart102;
        TLineSeries *LineSeries101;
        TChart *Chart103;
        TLineSeries *LineSeries102;
        TChart *Chart104;
        TLineSeries *LineSeries103;
        TChart *Chart105;
        TLineSeries *LineSeries104;
        TChart *Chart106;
        TLineSeries *LineSeries105;
        TTabSheet *TabBS;
        TScrollBox *ScrollBox14;
        TChart *Chart107;
        TLineSeries *LineSeries106;
        TChart *Chart108;
        TLineSeries *LineSeries107;
        TChart *Chart109;
        TLineSeries *LineSeries108;
        TChart *Chart110;
        TLineSeries *LineSeries109;
        TChart *Chart111;
        TLineSeries *LineSeries110;
        TChart *Chart112;
        TLineSeries *LineSeries111;
        TChart *Chart113;
        TLineSeries *LineSeries112;
        TChart *Chart114;
        TLineSeries *LineSeries113;
        TChart *Chart115;
        TLineSeries *LineSeries114;
        TChart *Chart116;
        TLineSeries *LineSeries115;
        TChart *Chart117;
        TLineSeries *LineSeries116;
        void __fastcall TabUFSShow(TObject *Sender);
        void __fastcall Chart1DblClick(TObject *Sender);
        void __fastcall Chart2DblClick(TObject *Sender);
        void __fastcall Chart3DblClick(TObject *Sender);
        void __fastcall Chart4DblClick(TObject *Sender);
        void __fastcall Chart5DblClick(TObject *Sender);
        void __fastcall TabFSShow(TObject *Sender);
        void __fastcall Chart6DblClick(TObject *Sender);
        void __fastcall Chart7DblClick(TObject *Sender);
        void __fastcall Chart8DblClick(TObject *Sender);
        void __fastcall TabSSShow(TObject *Sender);
        void __fastcall Chart9DblClick(TObject *Sender);
        void __fastcall Chart10DblClick(TObject *Sender);
        void __fastcall Chart11DblClick(TObject *Sender);
        void __fastcall Chart12DblClick(TObject *Sender);
        void __fastcall Chart13DblClick(TObject *Sender);
        void __fastcall Chart14DblClick(TObject *Sender);
        void __fastcall Chart15DblClick(TObject *Sender);
        void __fastcall Chart16DblClick(TObject *Sender);
        void __fastcall Chart17DblClick(TObject *Sender);
        void __fastcall Chart18DblClick(TObject *Sender);
        void __fastcall Chart19DblClick(TObject *Sender);
        void __fastcall TabSZSShow(TObject *Sender);
        void __fastcall Chart20DblClick(TObject *Sender);
        void __fastcall Chart21DblClick(TObject *Sender);
        void __fastcall Chart22DblClick(TObject *Sender);
        void __fastcall Chart23DblClick(TObject *Sender);
        void __fastcall Chart24DblClick(TObject *Sender);
        void __fastcall Chart25DblClick(TObject *Sender);
        void __fastcall Chart26DblClick(TObject *Sender);
        void __fastcall Chart27DblClick(TObject *Sender);
        void __fastcall Chart28DblClick(TObject *Sender);
        void __fastcall Chart29DblClick(TObject *Sender);
        void __fastcall Chart30DblClick(TObject *Sender);
        void __fastcall Chart31DblClick(TObject *Sender);
        void __fastcall Chart32DblClick(TObject *Sender);
        void __fastcall Chart33DblClick(TObject *Sender);
        void __fastcall Chart34DblClick(TObject *Sender);
        void __fastcall TabZSShow(TObject *Sender);
        void __fastcall Chart35DblClick(TObject *Sender);
        void __fastcall Chart36DblClick(TObject *Sender);
        void __fastcall Chart37DblClick(TObject *Sender);
        void __fastcall Chart38DblClick(TObject *Sender);
        void __fastcall Chart39DblClick(TObject *Sender);
        void __fastcall Chart40DblClick(TObject *Sender);
        void __fastcall Chart41DblClick(TObject *Sender);
        void __fastcall Chart42DblClick(TObject *Sender);
        void __fastcall TabZHZSShow(TObject *Sender);
        void __fastcall Chart43DblClick(TObject *Sender);
        void __fastcall Chart44DblClick(TObject *Sender);
        void __fastcall Chart45DblClick(TObject *Sender);
        void __fastcall Chart46DblClick(TObject *Sender);
        void __fastcall Chart47DblClick(TObject *Sender);
        void __fastcall Chart48DblClick(TObject *Sender);
        void __fastcall Chart49DblClick(TObject *Sender);
        void __fastcall Chart50DblClick(TObject *Sender);
        void __fastcall Chart51DblClick(TObject *Sender);
        void __fastcall Chart52DblClick(TObject *Sender);
        void __fastcall TabZHSShow(TObject *Sender);
        void __fastcall Chart53DblClick(TObject *Sender);
        void __fastcall Chart54ContextPopup(TObject *Sender,
          TPoint &MousePos, bool &Handled);
        void __fastcall Chart55DblClick(TObject *Sender);
        void __fastcall Chart56DblClick(TObject *Sender);
        void __fastcall Chart57DblClick(TObject *Sender);
        void __fastcall Chart58DblClick(TObject *Sender);
        void __fastcall Chart59DblClick(TObject *Sender);
        void __fastcall Chart60DblClick(TObject *Sender);
        void __fastcall Chart61DblClick(TObject *Sender);
        void __fastcall Chart62DblClick(TObject *Sender);
        void __fastcall Chart54DblClick(TObject *Sender);
        void __fastcall TabOSShow(TObject *Sender);
        void __fastcall Chart63DblClick(TObject *Sender);
        void __fastcall Chart64DblClick(TObject *Sender);
        void __fastcall Chart65DblClick(TObject *Sender);
        void __fastcall Chart66DblClick(TObject *Sender);
        void __fastcall Chart67DblClick(TObject *Sender);
        void __fastcall Chart68DblClick(TObject *Sender);
        void __fastcall Chart69DblClick(TObject *Sender);
        void __fastcall TabKSShow(TObject *Sender);
        void __fastcall Chart70DblClick(TObject *Sender);
        void __fastcall Chart71DblClick(TObject *Sender);
        void __fastcall Chart72DblClick(TObject *Sender);
        void __fastcall Chart73DblClick(TObject *Sender);
        void __fastcall Chart74DblClick(TObject *Sender);
        void __fastcall Chart75DblClick(TObject *Sender);
        void __fastcall Chart76DblClick(TObject *Sender);
        void __fastcall Chart77DblClick(TObject *Sender);
        void __fastcall TabIKSShow(TObject *Sender);
        void __fastcall Chart78DblClick(TObject *Sender);
        void __fastcall Chart79DblClick(TObject *Sender);
        void __fastcall Chart80DblClick(TObject *Sender);
        void __fastcall Chart81DblClick(TObject *Sender);
        void __fastcall Chart82DblClick(TObject *Sender);
        void __fastcall TabPSShow(TObject *Sender);
        void __fastcall Chart83DblClick(TObject *Sender);
        void __fastcall Chart84DblClick(TObject *Sender);
        void __fastcall Chart85DblClick(TObject *Sender);
        void __fastcall Chart86DblClick(TObject *Sender);
        void __fastcall Chart87DblClick(TObject *Sender);
        void __fastcall Chart88DblClick(TObject *Sender);
        void __fastcall Chart89DblClick(TObject *Sender);
        void __fastcall TabNSShow(TObject *Sender);
        void __fastcall Chart90DblClick(TObject *Sender);
        void __fastcall Chart91DblClick(TObject *Sender);
        void __fastcall Chart92DblClick(TObject *Sender);
        void __fastcall Chart93DblClick(TObject *Sender);
        void __fastcall Chart94DblClick(TObject *Sender);
        void __fastcall Chart95DblClick(TObject *Sender);
        void __fastcall Chart96DblClick(TObject *Sender);
        void __fastcall Chart97DblClick(TObject *Sender);
        void __fastcall Chart98DblClick(TObject *Sender);
        void __fastcall Chart99DblClick(TObject *Sender);
        void __fastcall Chart100DblClick(TObject *Sender);
        void __fastcall TabTSShow(TObject *Sender);
        void __fastcall Chart101DblClick(TObject *Sender);
        void __fastcall Chart102DblClick(TObject *Sender);
        void __fastcall Chart103DblClick(TObject *Sender);
        void __fastcall Chart104DblClick(TObject *Sender);
        void __fastcall Chart105DblClick(TObject *Sender);
        void __fastcall Chart106DblClick(TObject *Sender);
        void __fastcall TabBSShow(TObject *Sender);
        void __fastcall Chart107DblClick(TObject *Sender);
        void __fastcall Chart108DblClick(TObject *Sender);
        void __fastcall Chart109DblClick(TObject *Sender);
        void __fastcall Chart110DblClick(TObject *Sender);
        void __fastcall Chart111DblClick(TObject *Sender);
        void __fastcall Chart112DblClick(TObject *Sender);
        void __fastcall Chart113DblClick(TObject *Sender);
        void __fastcall Chart114DblClick(TObject *Sender);
        void __fastcall Chart115DblClick(TObject *Sender);
        void __fastcall Chart116DblClick(TObject *Sender);
        void __fastcall Chart117DblClick(TObject *Sender);
private:	// User declarations
public:
        bool flag_FindFirstUFS;
        TSearchRec srec_UFS;
        double lBegin;
        double lEnd;
        vector <filter> tranInd_UFS;
        AnsiString maskUFS;
        double deltaX;
        bool flag_ShowUFS;
        double thkns; 
        double n;
        bool flag_ShowFS;
        AnsiString maskFS;
        TSearchRec srec_FS;
        bool FindFirstFS;
        AnsiString maskSS;
        bool flag_ShowSS;
        bool flag_FindFirstSS;
        TSearchRec srec_SS;
        bool flag_ShowSZS;
        AnsiString maskSZS;
        bool flag_FindFirstSZS;
        TSearchRec srec_SZS;
        bool flag_ShowZS;
        bool flag_FindFirstZS;
        AnsiString maskZS;
        TSearchRec srec_ZS;
        bool flag_ShowZHZS;
        bool flag_FindFirstZHZS;
        AnsiString maskZHZS;
        TSearchRec srec_ZHZS;
        bool flag_ShowZHS;
        bool flag_FindFirstZHS;
        AnsiString maskZHS;
        TSearchRec srec_ZHS;
        bool flag_ShowOS;
        bool flag_FindFirstOS;
        AnsiString maskOS;
        TSearchRec srec_OS;
        bool flag_ShowKS;
        bool flag_FindFirstKS;
        AnsiString maskKS;
        TSearchRec srec_KS;
        bool flag_ShowIKS;
        bool flag_FindFirstIKS;
        AnsiString maskIKS;
        TSearchRec srec_IKS;
        bool flag_ShowPS;
        bool flag_FindFirstPS;
        AnsiString maskPS;
        TSearchRec srec_PS;
        bool flag_ShowNS;
        bool flag_FindFirstNS;
        AnsiString maskNS;
        TSearchRec srec_NS;
        bool flag_ShowTS;
        bool flag_FindFirstTS;
        AnsiString maskTS;
        TSearchRec srec_TS;
        bool flag_ShowBS;
        bool flag_FindFirstBS;
        AnsiString maskBS;
        TSearchRec srec_BS; 		// User declarations
        __fastcall TForm2(TComponent* Owner);
        AnsiString FindFilterFile(AnsiString mask);
        filter LoadData(AnsiString name);
        filter CalcTransmn(filter filOD, double thkn, double n);
        dot InterpLinear(filter fil, double x);
        void PlotData(filter data, TLineSeries * Series, TChart * Chart);
        void showUFS();
        void showFS();
        void showSS();
        void showSZS();
        void showZS();
        void showZHZS();
        void showZHS();
        void showOS();
        void showKS();
        void showIKS();
        void showPS();
        void showNS();
        void showTS();
        void showBS();
};
//---------------------------------------------------------------------------
extern PACKAGE TForm2 *Form2;
//---------------------------------------------------------------------------
#endif
